### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by christophbloemer0382** [neuland/pug4j#10]
Changes in transition to pug4j where made which broke windows support.

Especially the classpath handling currently doesn't work on a windows operating system.

Make sure tests on windows works again.

Todos:
* Find a solution to reproduce errors
* Fix TemplateLoader

**Comment by chbloemer** [comment]
Added github actions pipeline to run tests on windows and ubuntu.
Now the errors on windows are visible and I can start fixing them.
