### ISSUE TITLE
jexl3 dependency conflict

### ISSUE THREAD

**Issue by RayaneA7** [neuland/pug4j#12]
I have plenty of errors of this type when trying to use pug4J inside a javaFX project : 
`the unnamed module reads package org.apache.commons.jexl3 from both commons.jexl3 and pug4j
`
lot of modules which uses jexl3 causes conflicts because of jexl3 package's different versions inside the same project

**Comment by RayaneA7** [comment]
Note : I am using Gradle, and tried to import pug4j alongside with javafx

**Comment by chbloemer** [comment]
Please try out 2.1.0. I moved the jexl overrides into a different package.
