### ISSUE TITLE
Mixins - Default Argument's Values - is it working?

### ISSUE THREAD

**Issue by godzzo** [neuland/pug4j#14]
I tried to use mixins default argument values, as the [PugJS Documentation](https://github.com/pugjs/pug-en/blob/master/src/language/mixins.md#default-arguments-values) suggests, but not working with JEXL.

Should it be working, is it an implemented feature of Pug4J? Or is it an ExpressionEngine dependent feature?

There is an [Issue: Default values for arguments in mixins #743](https://github.com/pugjs/pug/issues/743#issuecomment-136243877), where a comment say it is Runtime dependent.

[Pug - mixins - default-arguments-values](https://github.com/pugjs/pug-en/blob/master/src/language/mixins.md#default-arguments-values)

```pug
//- Declaration
mixin article(title='Default Title')
  .article
    .article-wrapper
      h1= title

//- Use
+article()

+article('Hello world')
```

**Comment by chbloemer** [comment]
I implemented default variables on mixin arguments in version 2.1.0. Please try it out.
