### ISSUE TITLE
Can't find style.css - file url missing forwardslash?

### ISSUE THREAD

**Issue by astubbs** [neuland/pug4j#15]
Using the code in my .pug: include style.css

I get the error: 

the included file [style.css] could not be opened
Users/antony/IdeaProjects/X/target/classes/style.css (No such file or directory)

You can see it's missing a leading forward slash, otherwise it would have worked.

If I use:
include /Users/antony/IdeaProjects/X/target/classes/style.css

it works.

**Comment by chbloemer** [comment]
Can't reproduce in current versions.
