### ISSUE TITLE
Beta or GA?

### ISSUE THREAD

**Issue by adrogon** [neuland/pug4j#4]
Hello pug4j maintainers,

What are the next steps for your library? Will you release a beta or GA version at some point?

Also, the `master` branch currently holds `2.0.0-alpha-3`, but [mvnrepository](https://mvnrepository.com/artifact/de.neuland-bfi/pug4j) only holds the `2.0.0-alpha-2` version of your library. Would you mind releasing the latest?

Thanks in advance.

**Comment by chbloemer** [comment]
Just released an 2.0.0-alpha4. Hope it shows up in mvnrepository. This one should be very stable from feature perspective.
Code itself needs some cleanup and a final comparison to pug.js to name it beta. Just my point of view.
