### ISSUE TITLE
Bad syntax in expression causes index out of bounds exception

### ISSUE THREAD

**Issue by astubbs** [neuland/pug4j#6]
For example, trying to parse:

```
h1 #{variable'}
```

Throws index out of bounds exception. 

Fixed by #5

**Comment by chbloemer** [comment]
Just release 2.0.0-alpha4. I ported some of the error handling from pug.js over to java. You should now have some nicer error output. Don't mind that I don't need to merge your PR anymore.

**Comment by astubbs** [comment]
Awesome! thanks.
