### ISSUE TITLE
Vulnerability in 3rd party dependency "com.google.code.gson:gson" (update needed)

### ISSUE THREAD

**Issue by dbelyaev** [neuland/pug4j#8]
The current version of pug4j is using an outdated dependency with a known vulnerability `com.google.code.gson:gson@2.8.7` 
(introduced trough: `de.neuland-bfi:pug4j@2.0.3 > com.google.code.gson:gson@2.8.7`).

Vulnerability: "Deserialization of Untrusted Data" ([SNYK-JAVA-COMGOOGLECODEGSON-1730327](https://security.snyk.io/vuln/SNYK-JAVA-COMGOOGLECODEGSON-1730327)) ([CVSS 7.7](https://www.first.org/cvss/calculator/3.1#CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:H/A:H))

Please, upgrade `com.google.code.gson:gson` to version **2.8.9** or higher.

**Comment by chbloemer** [comment]
Fixed in 2.0.4
